// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 optimized-room.glb 
// */

// import { useGLTF, useTexture } from '@react-three/drei'
// import * as THREE from 'three';

// export function ModelRoom(props) {
//   const matcapTexture = useTexture('/images/textures/mat1.png');
//   const { nodes, materials } = useGLTF('/models/optimized-room.glb');
//   const curtainMaterial = new THREE.MeshStandardMaterial({
//     color: "#d90429",
//     side: THREE.DoubleSide,
//     shininess: 50,
//     emissive: "#220000",
//     specular: "white",
//     roughness: 0.5,
//     metalness: 0.2
//   });
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes._________6_blinn1_0.geometry} material={curtainMaterial} />
//       <mesh geometry={nodes.body1_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.cabin_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.chair_body_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.comp_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.emis_lambert1_0.geometry} material={materials.lambert1} />
//       <mesh geometry={nodes.handls_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.keyboard_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.kovrik_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.lamp_bl_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.lamp_white_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.miuse_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.monitor2_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.monitor3_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.pCylinder5_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.pillows_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.polySurface53_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.radiator_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.radiator_blinn1_0001.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.railing_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.red_bttns_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.red_vac_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.stylus_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.table_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.tablet_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.triangle_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.vac_black_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.vacuum1_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.vacuumgrey_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.vires_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.window_blinn1_0.geometry} material={materials.blinn1} />
//       <mesh geometry={nodes.window4_phong1_0.geometry} material={materials.phong1} />
//     </group>
//   )
// }

// useGLTF.preload('/models/optimized-room.glb')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from "three";

export function ModelRoom(props) {
  const { nodes, materials } = useGLTF("/models/optimized-room.glb");
  const screensRef = useRef();
  const matcapTexture = useTexture("/images/textures/mat1.png");

  const canvas = document.createElement("canvas");
canvas.width = 1024;
canvas.height = 512;

const ctx = canvas.getContext("2d");

// background
ctx.fillStyle = "#bffcff";
ctx.fillRect(0, 0, canvas.width, canvas.height);

// text
ctx.fillStyle = "#111";
ctx.font = "bold 60px Arial";
ctx.fillText("Hello Aman", 80, 120);

ctx.font = "36px Arial";
ctx.fillText("Three.js workstation", 80, 190);

const screenTexture = new THREE.CanvasTexture(canvas);

const screenMaterial = new THREE.MeshBasicMaterial({
  map: screenTexture
});

  const curtainMaterial = new THREE.MeshStandardMaterial({
     color: "#d90429",
     side: THREE.DoubleSide,
     shininess: 50,
     emissive: "#220000",
     specular: "white",
     roughness: 0.5,
     metalness: 0.2
  });

  const bodyMaterial = new THREE.MeshStandardMaterial({
    map: matcapTexture,
  });

  const tableMaterial = new THREE.MeshStandardMaterial({
    color: "#582f0e",
  });

  const radiatorMaterial = new THREE.MeshStandardMaterial({
    color: "#fff",
  });

  const compMaterial = new THREE.MeshStandardMaterial({
    color: "#fff",
  });

  const pillowMaterial = new THREE.MeshStandardMaterial({
    color: "#8338ec",
  });

  const chairMaterial = new THREE.MeshStandardMaterial({
    color: "#000",
  });

  return (
    <group {...props} dispose={null}>
      <EffectComposer>
        <SelectiveBloom
          selection={screensRef}
          intensity={1} // Strength of the bloom
          luminanceThreshold={0.2} // Minimum luminance needed
          luminanceSmoothing={0.9} // Smooth transition
          blendFunction={BlendFunction.ADD} // How it blends
        />
      </EffectComposer>
      <mesh
        geometry={nodes._________6_blinn1_0.geometry}
        material={curtainMaterial}
      />
      <mesh geometry={nodes.body1_blinn1_0.geometry} material={bodyMaterial} />
      <mesh geometry={nodes.cabin_blinn1_0.geometry} material={tableMaterial} />
      <mesh
        geometry={nodes.chair_body_blinn1_0.geometry}
        material={chairMaterial}
      />
      <mesh geometry={nodes.comp_blinn1_0.geometry} material={compMaterial} />
      <mesh
        ref={screensRef}
        geometry={nodes.emis_lambert1_0.geometry}
        material={screenMaterial}
      />
      <mesh
        geometry={nodes.handls_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.keyboard_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.kovrik_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_bl_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_white_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.miuse_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor2_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor3_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.pCylinder5_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.pillows_blinn1_0.geometry}
        material={pillowMaterial}
      />
      <mesh
        geometry={nodes.polySurface53_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0.geometry}
        material={radiatorMaterial}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0001.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.railing_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_bttns_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_vac_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.stylus_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh geometry={nodes.table_blinn1_0.geometry} material={tableMaterial} />
      <mesh
        geometry={nodes.tablet_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.triangle_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vac_black_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuum1_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuumgrey_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vires_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.window_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.window4_phong1_0.geometry}
        material={materials.phong1}
      />
    </group>
  );
}

useGLTF.preload("/models/optimized-room.glb");